### Create category
POST http://localhost:3000/categories
Content-Type: application/json

{
    "name": "Category 1",
    "description": "Description 1"
}


###
GET http://localhost:3000/categories

###
GET http://localhost:3000/categories/e2187439-5b34-447e-ab18-142dbe27e533

